/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_ce3c3227 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/ezsfzliblqsslqcnwdya/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import postgres from "npm:postgres@3.4.5";

const TABLE_NAME = "kv_store_ce3c3227";
const DB_URL = Deno.env.get("SUPABASE_DB_URL");
if (!DB_URL) {
  throw new Error("SUPABASE_DB_URL is not configured");
}

const sql = postgres(DB_URL, {
  max: 1,
  prepare: false,
});

let isTableReady = false;
let tableInitPromise: Promise<void> | null = null;

const ensureTable = async (): Promise<void> => {
  if (isTableReady) return;

  if (!tableInitPromise) {
    tableInitPromise = (async () => {
      await sql.unsafe(`
        CREATE TABLE IF NOT EXISTS ${TABLE_NAME} (
          key TEXT NOT NULL PRIMARY KEY,
          value JSONB NOT NULL
        )
      `);

      // Best effort to refresh PostgREST schema cache for external tools.
      try {
        await sql`NOTIFY pgrst, 'reload schema'`;
      } catch {
        // Ignore notify failures; direct SQL operations below do not require PostgREST.
      }

      isTableReady = true;
    })();
  }

  await tableInitPromise;
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  await ensureTable();
  await sql.unsafe(
    `
      INSERT INTO ${TABLE_NAME} (key, value)
      VALUES ($1, $2::jsonb)
      ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
    `,
    [key, JSON.stringify(value)],
  );
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  await ensureTable();
  const rows = await sql.unsafe<{ value: any }[]>(
    `
      SELECT value
      FROM ${TABLE_NAME}
      WHERE key = $1
      LIMIT 1
    `,
    [key],
  );
  return rows[0]?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  await ensureTable();
  await sql.unsafe(
    `
      DELETE FROM ${TABLE_NAME}
      WHERE key = $1
    `,
    [key],
  );
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  await ensureTable();
  if (keys.length !== values.length) {
    throw new Error("keys and values length mismatch");
  }

  for (let i = 0; i < keys.length; i++) {
    await sql.unsafe(
      `
        INSERT INTO ${TABLE_NAME} (key, value)
        VALUES ($1, $2::jsonb)
        ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
      `,
      [keys[i], JSON.stringify(values[i])],
    );
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  await ensureTable();
  if (keys.length === 0) {
    return [];
  }

  const rows = await sql.unsafe<{ value: any }[]>(
    `
      SELECT value
      FROM ${TABLE_NAME}
      WHERE key = ANY($1)
    `,
    [keys],
  );
  return rows.map((row) => row.value);
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  await ensureTable();
  if (keys.length === 0) {
    return;
  }

  await sql.unsafe(
    `
      DELETE FROM ${TABLE_NAME}
      WHERE key = ANY($1)
    `,
    [keys],
  );
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  await ensureTable();
  return await sql.unsafe<{ key: string; value: any }[]>(
    `
      SELECT key, value
      FROM ${TABLE_NAME}
      WHERE key LIKE $1
    `,
    [`${prefix}%`],
  );
};

// Search for key-value pairs by prefix plus regex key filter.
export const getByPrefixAndRegex = async (prefix: string, regex: string): Promise<any[]> => {
  await ensureTable();
  return await sql.unsafe<{ key: string; value: any }[]>(
    `
      SELECT key, value
      FROM ${TABLE_NAME}
      WHERE key LIKE $1
      AND key ~ $2
    `,
    [`${prefix}%`, regex],
  );
};

// Search for key-value pairs by prefix and exact key length.
export const getByPrefixAndLength = async (prefix: string, keyLength: number, limit = 5000): Promise<any[]> => {
  await ensureTable();
  return await sql.unsafe<{ key: string; value: any }[]>(
    `
      SELECT key, value
      FROM ${TABLE_NAME}
      WHERE key LIKE $1
      AND char_length(key) = $2
      LIMIT $3
    `,
    [`${prefix}%`, keyLength, limit],
  );
};
